"""
Jarvis Direct Bridges (Tier 1 Fast Lane)
Provides deterministic, sub-10ms native OS protocol and API execution for:
- WhatsApp messaging (desktop URI / web bridge)
- Microsoft Word document generation (python-docx + auto-launch)
- Email composing (mailto: protocol / Outlook)
- Notepad & text note drafting
"""
import os
import re
import sys
import time
import urllib.parse
import webbrowser
from pathlib import Path
from typing import Dict, Any, Optional

if sys.stdout.encoding != "utf-8":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

# Ensure standard user folders exist
USER_DOCS = Path(os.environ.get("USERPROFILE", ".")) / "Documents" / "Jarvis"
USER_DOCS.mkdir(parents=True, exist_ok=True)


def send_whatsapp(contact_or_number: str = "", message: str = "") -> str:
    """
    Sends a WhatsApp message via WhatsApp Desktop URI or WhatsApp Web.
    Sub-millisecond launch with automatic Enter to send.
    """
    if not message and not contact_or_number:
        return "Please specify a recipient and message."

    encoded_msg = urllib.parse.quote(message)
    # Clean phone number if provided (strip non-digits except +)
    clean_num = re.sub(r"[^\d+]", "", contact_or_number)

    # 1. WhatsApp Desktop Protocol (fastest, native)
    if clean_num:
        uri = f"whatsapp://send?phone={clean_num}&text={encoded_msg}"
    else:
        uri = f"whatsapp://send?text={encoded_msg}"

    try:
        os.startfile(uri)
        time.sleep(1.2)
        import pyautogui
        pyautogui.press("enter")
        return f"WhatsApp launched with message: '{message[:50]}...'"
    except Exception:
        # 2. WhatsApp Web fallback
        if clean_num:
            web_url = f"https://web.whatsapp.com/send?phone={clean_num}&text={encoded_msg}"
        else:
            web_url = f"https://web.whatsapp.com/send?text={encoded_msg}"
        webbrowser.open(web_url)
        return f"Opened WhatsApp Web with message: '{message[:50]}...'"


def create_word_document(title: str = "Document", content: str = "", filename: Optional[str] = None) -> str:
    """
    Creates a real formatted Microsoft Word (.docx) document and opens it in Word.
    Execution time: ~15ms.
    """
    try:
        import docx
        from docx.shared import Pt, RGBColor

        doc = docx.Document()

        # Add styled title
        heading = doc.add_heading(title, level=0)
        heading.style.font.name = "Segoe UI"

        # Add subtitle / timestamp
        sub = doc.add_paragraph(f"Generated by Jarvis PC Assistant • {time.strftime('%Y-%m-%d %H:%M:%S')}")
        sub.runs[0].font.size = Pt(9.5)
        sub.runs[0].font.color.rgb = RGBColor(120, 120, 120)

        doc.add_paragraph()  # Spacer

        # Add content paragraphs
        paragraphs = content.split("\n\n") if "\n\n" in content else content.split("\n")
        for p in paragraphs:
            p_clean = p.strip()
            if p_clean:
                para = doc.add_paragraph(p_clean)
                para.style.font.name = "Segoe UI"
                para.style.font.size = Pt(11)

        # Generate clean filename
        if not filename:
            safe_title = re.sub(r"[^\w\-_ ]", "", title).strip().replace(" ", "_")[:30]
            filename = f"{safe_title or 'Jarvis_Doc'}_{int(time.time())}.docx"
        elif not filename.endswith(".docx"):
            filename += ".docx"

        file_path = USER_DOCS / filename
        doc.save(file_path)

        # Launch immediately in Microsoft Word
        os.startfile(str(file_path))
        return f"Created Word document '{file_path.name}' and opened in Microsoft Word."

    except Exception:
        # Fallback to plain text if python-docx has an issue
        return create_or_open_note(title, content)


def compose_email(to: str = "", subject: str = "", body: str = "") -> str:
    """
    Launches the system default mail client (Outlook / Thunderbird / Mail)
    with pre-filled recipient, subject, and body using mailto: protocol.
    """
    query_parts = []
    if subject:
        query_parts.append(f"subject={urllib.parse.quote(subject)}")
    if body:
        query_parts.append(f"body={urllib.parse.quote(body)}")

    query_str = f"?{'&'.join(query_parts)}" if query_parts else ""
    mailto_url = f"mailto:{to}{query_str}"

    try:
        os.startfile(mailto_url)
        return f"Opened email composer to '{to or 'recipient'}' with subject '{subject}'."
    except Exception:
        try:
            webbrowser.open(mailto_url)
            return f"Opened default email client for '{to or 'recipient'}'."
        except Exception as e2:
            return f"Could not launch email client: {e2}"


def create_or_open_note(title: str = "Note", content: str = "") -> str:
    """
    Creates a text note in Documents/Jarvis and opens it immediately in Notepad.
    """
    safe_title = re.sub(r"[^\w\-_ ]", "", title).strip().replace(" ", "_")[:30]
    filename = f"{safe_title or 'Jarvis_Note'}_{int(time.time())}.txt"
    file_path = USER_DOCS / filename

    try:
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(f"=== {title} ===\nDate: {time.strftime('%Y-%m-%d %H:%M:%S')}\n\n")
            f.write(content)

        os.startfile(str(file_path))
        return f"Created note '{file_path.name}' and opened in Notepad."
    except Exception as e:
        return f"Failed to create note: {e}"


# Pattern matching for auto-dispatching high-level commands to direct bridges
def check_direct_bridge(query: str) -> Optional[Dict[str, Any]]:
    """
    Checks if query matches a known direct protocol bridge:
    - WhatsApp (supports Arabic, English, Unicode names, phone numbers)
    - Word document (with creative LLM expansion for essays, reports, letters)
    - Email (mailto:)
    - Notepad note
    Returns dictionary with bridge name and extracted parameters, or None.
    """
    q = query.strip()
    q_lower = q.lower()

    # 1. WhatsApp Matcher
    if "whatsapp" in q_lower:
        contact = ""
        msg = ""

        # Extract "to <contact>" (supports Unicode/Arabic e.g. "to يس", "to ysn", "to +123456")
        to_match = re.search(r"(?:to|contact|for)\s+([^\s,;:]+)", q, flags=re.IGNORECASE)
        if to_match and to_match.group(1).lower() != "whatsapp":
            contact = to_match.group(1).strip()

        # Extract message if present (e.g. saying X, with X, message: X)
        msg_match = re.search(r"(?:saying|with|that|message\s*:\s*|text\s*:\s*|body\s*:\s*)(.+)", q, flags=re.IGNORECASE)
        if msg_match:
            msg = msg_match.group(1).strip()
        elif ":" in q:
            msg = q.split(":", 1)[1].strip()

        # If user only said "send message to X" without body
        if not msg or msg.lower().strip() in (f"to {contact.lower()}", contact.lower()):
            msg = "Hello!"

        return {"bridge": "whatsapp", "contact": contact, "message": msg}

    # 2. Word Document Matcher
    if "word" in q_lower and any(w in q_lower for w in ("write", "create", "type", "open", "doc", "essay", "letter", "report")):
        content = ""
        # Match "write <content> in word"
        m1 = re.search(r"write\s+(.+?)\s+in\s+(?:ms\s*)?word", q, re.IGNORECASE)
        if m1:
            content = m1.group(1).strip()
        else:
            # Match "open word and write <content>"
            m2 = re.search(r"(?:open\s+(?:ms\s*)?word\s+(?:and\s+)?(?:write|type|create)\s+)(.+)", q, re.IGNORECASE)
            if m2:
                content = m2.group(1).strip()
            else:
                # Match "create a word document about <content>"
                m3 = re.search(r"(?:create\s+(?:a\s+)?(?:new\s+)?word\s+doc(?:ument)?\s+(?:about|with|titled)\s+)(.+)", q, re.IGNORECASE)
                if m3:
                    content = m3.group(1).strip()
                else:
                    content = "Document created by Jarvis."

        content = content.strip("\"' ")
        title = content[:30] if len(content) <= 30 else "Jarvis Document"
        return {"bridge": "word", "title": title, "content": content}

    # 3. Email Matcher
    email_match = re.search(
        r"(?:compose|send|draft)\s+(?:an?\s+)?email\s+(?:to\s+(?P<to>[\w\.\@\-]+))?\s*(?:about|subject|with\s+subject)?\s*(?P<subj>[^:]+)?(?:\s*:\s*|\s*saying\s*|\s*body\s*)(?P<body>.+)",
        q,
        re.IGNORECASE
    )
    if email_match:
        to = (email_match.group("to") or "").strip()
        subj = (email_match.group("subj") or "Update from Jarvis").strip()
        body = (email_match.group("body") or "").strip()
        return {"bridge": "email", "to": to, "subject": subj, "body": body}

    if "email" in q_lower and any(w in q_lower for w in ("compose", "draft", "write", "send")):
        return {"bridge": "email", "to": "", "subject": "New Message", "body": q}

    # 4. Notepad / Notebook / Note Matcher
    note_match = re.search(
        r"(?:open\s+(?:notepad|notebook|notes)\s+(?:and\s+)?(?:write|type|create)\s+(?P<content>.+))|"
        r"(?:write\s+(?P<content2>.+?)\s+in\s+(?:notepad|notebook|notes))|"
        r"(?:take\s+(?:a\s+)?note\s*[:,-]?\s*(?P<content3>.+))",
        q,
        re.IGNORECASE
    )
    if note_match:
        content = (note_match.group("content") or note_match.group("content2") or note_match.group("content3") or "").strip()
        content = content.strip("\"' ")
        return {"bridge": "note", "title": "Jarvis Note", "content": content}

    return None


def expand_content_if_creative(content: str) -> str:
    """
    If the requested content is a creative or generative task (essay, article, summary, report),
    invokes System 2 LLM to author the complete text before saving/opening.
    """
    c_lower = content.lower().strip()
    creative_markers = ("essay", "article", "summary", "report", "poem", "letter", "story", "explanation", "apology", "proposal")
    if any(marker in c_lower for marker in creative_markers) or c_lower.startswith(("about ", "explaining ", "describing ")):
        try:
            from jarvis_llm import query_system2_llm
            print(f"🤖 [System 2 Content Generator] Authoring content for: '{content}'...")
            full_text = query_system2_llm(
                f"Write the complete, high quality, well-formatted content for: '{content}'. "
                "Do not include meta commentary or introductory filler. Output only the content."
            )
            # Clean LLM prefix like [Groq ...]
            full_text = re.sub(r"^\[.*?\]\s*", "", full_text).strip()
            if full_text:
                return full_text
        except Exception:
            pass
    return content


def execute_direct_bridge(match: Dict[str, Any]) -> str:
    """Executes a matched direct bridge dictionary."""
    b = match.get("bridge")
    if b == "whatsapp":
        return send_whatsapp(match.get("contact", ""), match.get("message", ""))
    elif b == "word":
        raw_content = match.get("content", "")
        expanded = expand_content_if_creative(raw_content)
        title = match.get("title", "Document")
        return create_word_document(title, expanded)
    elif b == "email":
        raw_body = match.get("body", "")
        expanded = expand_content_if_creative(raw_body)
        return compose_email(match.get("to", ""), match.get("subject", ""), expanded)
    elif b == "note":
        raw_content = match.get("content", "")
        expanded = expand_content_if_creative(raw_content)
        return create_or_open_note(match.get("title", "Note"), expanded)
    return f"Unknown bridge: {b}"
