"""
Laya Tier 1 Native Tools
Fast, reliable, direct execution for Microsoft Office (Word, Excel), Notepad,
WhatsApp, and Email automation.
"""

import os
import sys
import time
import urllib.parse
import datetime
import subprocess
from pathlib import Path
from typing import Optional, Dict, Any, List

import docx
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

from laya.config import DOCS_DIR


class Tier1NativeTools:
    _instance: Optional["Tier1NativeTools"] = None

    @classmethod
    def get_instance(cls) -> "Tier1NativeTools":
        if cls._instance is None:
            cls._instance = cls()
        return cls._instance

    # -------------------------------------------------------------
    # 1. Microsoft Word Generation (.docx)
    # -------------------------------------------------------------
    def create_word_document(self, topic: str = "Document", content: Optional[str] = None) -> str:
        doc = docx.Document()
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_topic = "".join(c if c.isalnum() else "_" for c in topic)[:40].strip("_") or "Document"
        filepath = DOCS_DIR / f"{safe_topic}_{timestamp}.docx"

        # Styled Title
        title_p = doc.add_paragraph()
        title_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = title_p.add_run(topic.title())
        run.bold = True
        run.font.size = Pt(22)
        run.font.color.rgb = RGBColor(31, 78, 121)

        # Subtitle / Timestamp
        sub_p = doc.add_paragraph()
        sub_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        sub_run = sub_p.add_run(f"Generated by Laya Desktop Assistant — {datetime.datetime.now().strftime('%B %d, %Y')}")
        sub_run.italic = True
        sub_run.font.size = Pt(10)
        sub_run.font.color.rgb = RGBColor(128, 128, 128)
        doc.add_paragraph()

        # Body Sections
        doc.add_heading("1. Executive Overview", level=1)
        if content:
            doc.add_paragraph(content)
        else:
            doc.add_paragraph(
                f"This document provides a comprehensive exploration of {topic}. "
                "Synthesized autonomously by Laya to support research, documentation, and operational planning."
            )

        doc.add_heading("2. Core Analysis & Key Insights", level=1)
        doc.add_paragraph(
            f"When analyzing {topic}, several core principles emerge as fundamental to success and long-term sustainability:"
        )
        bullet_points = [
            f"Strategic Foundation: Aligning objectives with {topic} best practices.",
            f"Operational Execution: Implementing scalable processes and robust monitoring.",
            f"Future Outlook: Anticipating advancements and integrating automated workflows.",
        ]
        for pt in bullet_points:
            doc.add_paragraph(pt, style="List Bullet")

        doc.add_heading("3. Actionable Recommendations", level=1)
        doc.add_paragraph(
            f"To achieve optimal results in {topic}, continuous iteration and data-driven reviews are strongly advised."
        )

        doc.save(str(filepath))
        try:
            os.startfile(str(filepath))
        except Exception:
            pass

        return f"Created Microsoft Word document '{filepath.name}' and opened it."

    # -------------------------------------------------------------
    # 2. Microsoft Excel Generation (.xlsx)
    # -------------------------------------------------------------
    def create_excel_sheet(self, topic: str = "Spreadsheet", headers: Optional[List[str]] = None, rows: Optional[List[List[Any]]] = None) -> str:
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = topic.title()[:28]

        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_topic = "".join(c if c.isalnum() else "_" for c in topic)[:40].strip("_") or "Sheet"
        filepath = DOCS_DIR / f"{safe_topic}_{timestamp}.xlsx"

        if not headers:
            headers = ["Item #", "Description", "Category", "Quantity", "Unit Cost ($)", "Total ($)"]
            rows = [
                [1, f"{topic.title()} Setup", "Initial", 1, 250.00, "=D2*E2"],
                [2, "Infrastructure & Hardware", "Operations", 2, 450.00, "=D3*E3"],
                [3, "Software Licensing", "Recurring", 5, 35.00, "=D4*E4"],
                [4, "Quality Assurance", "Services", 3, 120.00, "=D5*E5"],
                [5, "Contingency Buffer", "Reserve", 1, 150.00, "=D6*E6"],
            ]

        # Style Definitions
        header_fill = PatternFill(start_color="1F4E79", end_color="1F4E79", fill_type="solid")
        header_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
        regular_font = Font(name="Calibri", size=11)
        bold_font = Font(name="Calibri", size=11, bold=True)
        thin_border = Border(
            left=Side(style='thin', color='D9D9D9'),
            right=Side(style='thin', color='D9D9D9'),
            top=Side(style='thin', color='D9D9D9'),
            bottom=Side(style='thin', color='D9D9D9')
        )

        # Write Headers
        ws.append(headers)
        for col_idx in range(1, len(headers) + 1):
            cell = ws.cell(row=1, column=col_idx)
            cell.fill = header_fill
            cell.font = header_font
            cell.alignment = Alignment(horizontal="center", vertical="center")

        # Write Rows
        for row in rows:
            ws.append(row)

        # Format Cells
        for r_idx in range(2, len(rows) + 2):
            for c_idx in range(1, len(headers) + 1):
                cell = ws.cell(row=r_idx, column=c_idx)
                cell.font = regular_font
                cell.border = thin_border
                if c_idx in [5, 6]:
                    cell.number_format = '$#,##0.00'

        # Summary Total Row
        total_row_idx = len(rows) + 2
        ws.cell(row=total_row_idx, column=2, value="Grand Total").font = bold_font
        total_cell = ws.cell(row=total_row_idx, column=6, value=f"=SUM(F2:F{total_row_idx-1})")
        total_cell.font = bold_font
        total_cell.number_format = '$#,##0.00'

        # Auto-adjust column widths
        for col in ws.columns:
            max_len = max(len(str(cell.value or '')) for cell in col)
            col_letter = get_column_letter(col[0].column)
            ws.column_dimensions[col_letter].width = max(max_len + 4, 12)

        wb.save(str(filepath))
        try:
            os.startfile(str(filepath))
        except Exception:
            pass

        return f"Created Microsoft Excel workbook '{filepath.name}' and opened it."

    # -------------------------------------------------------------
    # 3. Notepad Note Generation (.txt)
    # -------------------------------------------------------------
    def create_notepad_note(self, content: str, filename: Optional[str] = None) -> str:
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        name = filename or f"note_{timestamp}.txt"
        if not name.endswith(".txt"):
            name += ".txt"
        filepath = DOCS_DIR / name

        header = f"--- LAYA NOTE [{datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] ---\n\n"
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(header + content + "\n")

        try:
            os.startfile(str(filepath))
        except Exception:
            pass

        return f"Created note '{name}' and opened it in Notepad."

    # -------------------------------------------------------------
    # 4. WhatsApp Automation
    # -------------------------------------------------------------
    def send_whatsapp(self, contact: str, message: str) -> str:
        import pyautogui
        import win32clipboard

        # Inject into Windows clipboard to support Unicode / Arabic / Emoji flawlessly
        win32clipboard.OpenClipboard()
        win32clipboard.EmptyClipboard()
        win32clipboard.SetClipboardText(message, win32clipboard.CF_UNICODETEXT)
        win32clipboard.CloseClipboard()

        # Launch WhatsApp URI or protocol
        url = f"whatsapp://send?text={urllib.parse.quote(message)}"
        try:
            os.startfile(url)
            time.sleep(1.2)
            pyautogui.press("enter")
            return f"Dispatched WhatsApp message to '{contact}': {message}"
        except Exception as e:
            return f"WhatsApp protocol invocation returned: {e}"

    # -------------------------------------------------------------
    # 5. Email Drafting
    # -------------------------------------------------------------
    def send_email(self, recipient: str, subject: str = "Message from Laya", body: str = "") -> str:
        enc_sub = urllib.parse.quote(subject)
        enc_body = urllib.parse.quote(body)
        mailto_url = f"mailto:{recipient}?subject={enc_sub}&body={enc_body}"
        try:
            os.startfile(mailto_url)
            return f"Opened email draft to {recipient} with subject '{subject}'."
        except Exception as e:
            return f"Failed to open email composer: {e}"

    # -------------------------------------------------------------
    # 6. Web & Media Search
    # -------------------------------------------------------------
    def web_search(self, query: str) -> str:
        url = f"https://www.google.com/search?q={urllib.parse.quote(query)}"
        try:
            os.startfile(url)
            return f"Searching Google for '{query}'."
        except Exception as e:
            return f"Failed to open search: {e}"

    def youtube_search(self, query: str) -> str:
        url = f"https://www.youtube.com/results?search_query={urllib.parse.quote(query)}"
        try:
            os.startfile(url)
            return f"Opening YouTube and searching for '{query}'."
        except Exception as e:
            return f"Failed to search YouTube: {e}"

    def open_url(self, url: str) -> str:
        if not url.startswith(("http://", "https://")):
            url = f"https://{url}"
        try:
            os.startfile(url)
            return f"Opened {url}."
        except Exception as e:
            return f"Failed to open URL: {e}"


def get_tier1_tools() -> Tier1NativeTools:
    return Tier1NativeTools.get_instance()
